name:                kalina
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/gnull/kalina#readme
license:             BSD3
author:              Ivan Oleynikov
maintainer:          ivan.oleynikov95@gmail.com
copyright:           2020 Ivan Oleynikov
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - wreq >= 0.5 && < 1
  - http-client >= 0.6 && < 1
  - feed >= 1.2 && < 2
  - lens >= 4.17 && < 5
  - bytestring >= 0.10 && < 1
  - text >= 1.2 && < 2
  - brick >= 0.47 && < 1
  - vty >= 5.25 && < 6
  - optparse-applicative >= 0.15 && < 1
  - directory >= 1.3 && < 2
  - filepath >= 1.4 && < 2
  - async >= 2.2 && < 3
  - safe-exceptions >= 0.1 && < 2
  - process >= 1.6 && < 2
  - pandoc >= 2.3 && < 3
  - containers >= 0.6 && < 1
  - binary >= 0.8 && < 1
  - time
  - mtl >= 2.2 && <3
  - either >= 5.0 && <6

ghc-options:
- -Wall -threaded

library:
  source-dirs: src _src
  exposed-modules:
  - State_
  - MZipper_
  - Actions_
  - Utility_
  - GenericFeed
  - GenericFeed.Binary
  - State
  - State.Menu
  - State.Fetch
  - Concurrency
  - Interface
  - Interface.Actions

executables:
  kalina:
    source-dirs:      app/
    main:             Main.hs
    dependencies:     kalina
