name:                rss-test
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/rss-test#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2019 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - wreq >= 0.5 && < 1
  - http-client >= 0.6 && < 1
  - feed >= 1.2 && < 2
  - lens >= 4.17 && < 5
  - bytestring >= 0.10 && < 1
  - text >= 1.2 && < 2
  - brick >= 0.47 && < 1
  - vty >= 5.25 && < 6
  - optparse-applicative >= 0.15 && < 1
  - directory >= 1.3 && < 2
  - filepath >= 1.4 && < 2
  - async >= 2.2 && < 3
  - safe-exceptions >= 0.1 && < 2
  - process >= 1.6 && < 2
  - pandoc >= 2.3 && < 3

ghc-options:
- -Wall -threaded

library:
  source-dirs: src
  exposed-modules:
  - GenericFeed
  - Menu
  - Concurrency
  - Interface
  - Actions

executables:
  news-view:
    source-dirs:      app/
    main:             Main.hs
    dependencies:     rss-test
